### ISSUE TITLE
train on gpu

### ISSUE THREAD

**Issue by rubick1896** [patrick-kidger/NeuralCDE#1]
In the example, train_coeff is wrapped in a python list. How do I move this thing to the GPU so the entire model can be trained on a GPU

**Comment by patrick-kidger** [comment]
It's a tuple of PyTorch Tensors, so just iterate through it calling `.to`:
`train_coeffs = tuple(x.to('cuda') for x in train_coeffs)`

Don't forget to move `model` and `train_t` to the GPU as well.
