### ISSUE TITLE
Dealing with 2D data

### ISSUE THREAD

**Issue by abduallahmohamed** [patrick-kidger/NeuralCDE#7]
Hi, 

Thanks for the great work which targets a real issue of Neural ODE. 
I was wondering if there's any example dealing with 2D data. For example an image where the architecture only uses Conv2D layers? 

Thanks

**Comment by patrick-kidger** [comment]
Not sure what you mean by this. How do you plan to process 2D data sequentially?

**Comment by abduallahmohamed** [comment]
For example if you have data in the format: (batch, time dimension, feature, subfeatures) 
Aka an Image like but the feature channel is a time dimension.

**Comment by patrick-kidger** [comment]
Relative to the standard (batch, time, channel) format, then you're asking about having the channels in two different axes?
There's no (mathematical) reason you can't do that, it's just a shape thing.

If you're needing compatibility with my code (or anyone else's), then you can always flatten/unflatten (batch, time, feature, subfeature) <-> (batch, time, feature * subfeature) at the appropriate points.

**Comment by abduallahmohamed** [comment]
Thanks, I totally understand this as this can work with your code. 
But in my case the (batch, time dimension, **feature**, **subfeatures**) can change from a batch to batch, thus the usage of Linear layers will be incompatible, same with your code. This is why I was looking for an example that's totally built on Conv2d layers.

**Comment by abduallahmohamed** [comment]
I think using a Conv1D can solve this issue and it will be compatible with your code, yet the spatial configurations will be lost.
Thanks

**Comment by patrick-kidger** [comment]
I think conv2d should work. As I say, flatten before interacting with things like cdeint, and unflatten as the first operation inside the vector field (before calling conv2d or whatever).
