### ISSUE TITLE
Forecasting a time series

### ISSUE THREAD

**Issue by abduallahmohamed** [patrick-kidger/NeuralCDE#9]
Hi, 
Thanks for your work. 

I was wondering about a case like this: 
You have your data which recorded between 0.0->2.0 seconds.
You try to predict the next 2 seconds aka, from 2.0 to 4.0 for example. 
In your example:
```
  z_T = torchcde.cdeint(X=X,
                        z0=z0,
                        func=self.func,
                        t=[2.0,2.5,3.0,3.5,4.0])
```
is it valid to set `t=[2.0,2.5,3.0,3.5,4.0]` even though the supplied observations are in range 0.0->2.0 sec? 
Or I have to solve the whole thing, aka insert an input from 0.0 ->4.0 with missing data points between 2.0->4.0? 

Thanks

**Comment by patrick-kidger** [comment]
I think you're going about this in the wrong way. Neural CDEs are essentially "continuous time RNNs", so have a think about how you'd solve the problem using RNNs first -- then switch them out for differential equations.

In this case, CDEs take a path as an input. If your path isn't defined in the region [2, 4], then how can it take it as an input?

What you probably want is a seq2seq model. Run a CDE over the region [0, 2]. Use the result of that as an initial condition for an ODE over the region [2, 4].

**Comment by abduallahmohamed** [comment]
I think I miss phrases my goal, let me restate it: 
X = my input which is within time [0,2] sec
y = my target which is withing time[2,4]

Can I integrate over `cdeint` t=[2,4] even if the input is only within [0,2]?

**Comment by patrick-kidger** [comment]
And what I'm saying is that the answer is no. You should integrate over [0,2] only.

**Comment by abduallahmohamed** [comment]
Thanks, makes sense what u said earlier about seq2seq!
